# Generated by Django 5.1.2 on 2025-01-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_newarrival'),
    ]

    operations = [
        migrations.DeleteModel(
            name='newarrival',
        ),
        migrations.AddField(
            model_name='product',
            name='Adidas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='Newbalance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='Nike',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='Puma',
            field=models.BooleanField(default=False),
        ),
    ]
